"""empty message

Revision ID: 2aca29e6bfed
Revises: ed543639f691
Create Date: 2020-10-11 00:16:57.022312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aca29e6bfed'
down_revision = 'ed543639f691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_university_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'university_id')
    op.drop_table('university')
    op.alter_column('course', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('course_university_id_fkey', 'course', 'university', ['university_id'], ['id'], ondelete='CASCADE')
    op.alter_column('course', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('university',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='university_pkey')
    )
    # ### end Alembic commands ###
