"""empty message

Revision ID: ad87d8012cda
Revises: a180e07e8116
Create Date: 2020-10-07 07:54:20.496512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad87d8012cda'
down_revision = 'a180e07e8116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('university_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'university_name')
    # ### end Alembic commands ###
