"""empty message

Revision ID: ed543639f691
Revises: aedc18ae4103
Create Date: 2020-10-07 09:58:23.381582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed543639f691'
down_revision = 'aedc18ae4103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.drop_constraint('course_domain_fkey', 'course', type_='foreignkey')
    op.drop_constraint('course_platform_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'platform', ['platform_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course', 'domain', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_column('course', 'domain')
    op.drop_column('course', 'platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('platform', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('domain', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_platform_fkey', 'course', 'platform', ['platform'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('course_domain_fkey', 'course', 'domain', ['domain'], ['id'], ondelete='CASCADE')
    op.drop_column('course', 'platform_id')
    op.drop_column('course', 'domain_id')
    # ### end Alembic commands ###
