"""empty message

Revision ID: aedc18ae4103
Revises: c554963250f4
Create Date: 2020-10-07 09:53:07.647897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedc18ae4103'
down_revision = 'c554963250f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_name', sa.String(), nullable=True))
    op.drop_column('course', 'course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('course', 'course_name')
    # ### end Alembic commands ###
