"""empty message

Revision ID: c554963250f4
Revises: e6706378eab9
Create Date: 2020-10-07 08:15:02.142598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c554963250f4'
down_revision = 'e6706378eab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('domain_name', sa.String(), nullable=True))
    op.drop_column('domain', 'platform_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('domain', 'domain_name')
    # ### end Alembic commands ###
