"""empty message

Revision ID: e6706378eab9
Revises: ad87d8012cda
Create Date: 2020-10-07 08:14:15.999866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6706378eab9'
down_revision = 'ad87d8012cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('university_id', sa.Integer(), nullable=False))
    op.drop_constraint('course_university_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'university', ['university_id'], ['id'], ondelete='CASCADE')
    op.drop_column('course', 'university')
    op.add_column('domain', sa.Column('platform_name', sa.String(), nullable=True))
    op.add_column('platform', sa.Column('platform_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform', 'platform_name')
    op.drop_column('domain', 'platform_name')
    op.add_column('course', sa.Column('university', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_university_fkey', 'course', 'university', ['university'], ['id'], ondelete='CASCADE')
    op.drop_column('course', 'university_id')
    # ### end Alembic commands ###
